### ISSUE TITLE
Qiskit version problem

### ISSUE THREAD

**Issue by QuantumY-CHN** [salvatorezam/quantum-swarm-path-planning#1]
Thank you for your fantastic work! I'm currently trying to follow this work. May I ask about the Qiskit version you were validated on? Great thanks!

**Comment by salvatorezam** [comment]
Hi! I unfortunately do no recall the exact Qiskit version used to develop this code, also, I now have a new laptop, and therefore no possibility of getting to my old environment. 

What I can tell you is that this work was developed during the first half of 2022, so tracing back to the official releases (https://github.com/Qiskit/qiskit/releases), it should be somewhere around version 0.19 to 0.21. Hope this helps

**Comment by QuantumY-CHN** [comment]
Thanks!
